# Generated by Django 3.2.20 on 2023-08-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0033_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.comment',),
        ),
        migrations.CreateModel(
            name='DefaultImageForAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.defaultimage',),
        ),
        migrations.CreateModel(
            name='FavoriteSitesForAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.favoritesites',),
        ),
        migrations.CreateModel(
            name='HourRangeForAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.hourrange',),
        ),
        migrations.CreateModel(
            name='ImageSizeForAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.imagesize',),
        ),
        migrations.CreateModel(
            name='ScheduleForAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.schedule',),
        ),
        migrations.CreateModel(
            name='SpecialScheduleForAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.specialschedule',),
        ),
        migrations.CreateModel(
            name='VideoSizeForAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.videosize',),
        ),
    ]
