# Generated by Django 3.2.20 on 2023-08-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentforadmin',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='defaultimageforadmin',
            options={'verbose_name': 'Default Image', 'verbose_name_plural': 'Default Images'},
        ),
        migrations.AlterModelOptions(
            name='favoritesitesforadmin',
            options={'verbose_name': 'Favorite Site', 'verbose_name_plural': 'Favorite Sites'},
        ),
        migrations.AlterModelOptions(
            name='hourrangeforadmin',
            options={'verbose_name': 'Hour Range', 'verbose_name_plural': 'Hour Ranges'},
        ),
        migrations.AlterModelOptions(
            name='imagesizeforadmin',
            options={'verbose_name': 'Image Size', 'verbose_name_plural': 'Image Sizes'},
        ),
        migrations.AlterModelOptions(
            name='scheduleforadmin',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterModelOptions(
            name='specialscheduleforadmin',
            options={'verbose_name': 'Special Schedule', 'verbose_name_plural': 'Special Schedules'},
        ),
        migrations.AlterModelOptions(
            name='videosizeforadmin',
            options={'verbose_name': 'Video Size', 'verbose_name_plural': 'Video Sizes'},
        ),
    ]
