# Generated by Django 3.2.25 on 2025-01-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('sites', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.comment',),
        ),
        migrations.CreateModel(
            name='DefaultImageForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Default Image',
                'verbose_name_plural': 'Default Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.defaultimage',),
        ),
        migrations.CreateModel(
            name='FavoriteSitesForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Favorite Site',
                'verbose_name_plural': 'Favorite Sites',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.favoritesites',),
        ),
        migrations.CreateModel(
            name='HourRangeForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Hour Range',
                'verbose_name_plural': 'Hour Ranges',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.hourrange',),
        ),
        migrations.CreateModel(
            name='ImageSizeForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Image Size',
                'verbose_name_plural': 'Image Sizes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.imagesize',),
        ),
        migrations.CreateModel(
            name='ScheduleForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.schedule',),
        ),
        migrations.CreateModel(
            name='SpecialScheduleForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Special Schedule',
                'verbose_name_plural': 'Special Schedules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.specialschedule',),
        ),
        migrations.CreateModel(
            name='VideoSizeForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Video Size',
                'verbose_name_plural': 'Video Sizes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.videosize',),
        ),
        migrations.AddField(
            model_name='translateddefaulttext',
            name='defautl_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='operations.defaulttext'),
        ),
        migrations.AddField(
            model_name='translateddefaulttext',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language'),
        ),
    ]
