# Generated by Django 3.2.20 on 2023-08-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20230802_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentforadmin',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
