# Generated by Django 3.2.21 on 2024-05-10 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_translatedlanguage'),
        ('operations', '0005_privacypolicies'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedDefaultText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Translated Text')),
                ('defautl_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='operations.defaulttext')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
