# Generated by Django 3.2.13 on 2023-07-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0033_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.site',),
        ),
    ]
