# Generated by Django 3.2.21 on 2024-02-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0041_site_always_open'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.translatedsite',),
        ),
    ]
