# Generated by Django 3.2.25 on 2025-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=50, verbose_name='Platform')),
                ('version', models.CharField(max_length=150, verbose_name='Version')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=50, unique=True, verbose_name='Platform')),
                ('url', models.CharField(max_length=200, verbose_name='Store url')),
            ],
        ),
        migrations.CreateModel(
            name='UserAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
