# Generated by Django 3.2.12 on 2022-03-01 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=50, verbose_name='Platform')),
                ('version', models.CharField(max_length=150, verbose_name='Version')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=50, unique=True, verbose_name='Platform')),
                ('url', models.CharField(max_length=200, verbose_name='Store url')),
            ],
        ),
        migrations.CreateModel(
            name='UserAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_version', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app_version.appversion', verbose_name='Version')),
            ],
        ),
    ]
