# Generated by Django 3.2.13 on 2023-05-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0004_auto_20230505_1125'),
        ('sites', '0019_defaultimage'),
        ('users', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='cities.city', verbose_name='City')),
                ('stops', models.ManyToManyField(to='sites.Site', verbose_name='Stops')),
                ('tags', models.ManyToManyField(to='users.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
    ]
