# Generated by Django 3.2.13 on 2023-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_top_ten',
            field=models.BooleanField(default=False, verbose_name='Is top 10'),
        ),
        migrations.AddField(
            model_name='route',
            name='num_of_views',
            field=models.IntegerField(default=0, verbose_name='Number of times viewed'),
        ),
    ]
