# Generated by Django 3.2.25 on 2025-01-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('sites', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='sites.site'),
        ),
        migrations.AddField(
            model_name='route',
            name='cities',
            field=models.ManyToManyField(related_name='routes', to='cities.City', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(related_name='routes', through='routes.RouteStop', to='sites.Site', verbose_name='Stops'),
        ),
    ]
