# Generated by Django 3.2.25 on 2025-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('routes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='tags',
            field=models.ManyToManyField(related_name='routes', to='users.Tag', verbose_name='Tags'),
        ),
    ]
