# Generated by Django 3.2.13 on 2023-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20230526_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
