# Generated by Django 3.2.13 on 2023-05-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_route_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('is_top_ten', 'num_of_views'), 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
    ]
