# Generated by Django 3.2.20 on 2023-10-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_phone_prefix'),
        ('routes', '0004_alter_route_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='tags',
            field=models.ManyToManyField(related_name='routes', to='users.Tag', verbose_name='Tags'),
        ),
    ]
