# Generated by Django 3.2.20 on 2023-10-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_translatedfield_translation'),
        ('routes', '0006_auto_20231018_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='route',
            name='title_es',
        ),
        migrations.CreateModel(
            name='TranslatedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Translated Title')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='routes.route')),
            ],
        ),
    ]
