# Generated by Django 3.2.21 on 2023-12-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0040_auto_20231124_0841'),
        ('routes', '0010_auto_20231027_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(related_name='routes', to='sites.Site', verbose_name='Stops'),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
