# Generated by Django 3.2.21 on 2023-12-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0040_auto_20231124_0841'),
        ('routes', '0013_remove_route_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(related_name='routes', through='routes.RouteStop', to='sites.Site', verbose_name='Stops'),
        ),
    ]
