# Generated by Django 3.2.21 on 2023-12-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0014_route_stops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ('order',)},
        ),
    ]
