# Generated by Django 3.2.21 on 2023-12-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0040_auto_20231124_0841'),
        ('routes', '0016_alter_routestop_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='sites.site'),
        ),
    ]
