version: '3.3'

services:

  # Webapp

  app:
    container_name: localsecrets_app
    restart: always
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - .:/code
    env_file: .docker/environments/local.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "0.0.0.0:80:8000"
    depends_on:
      - db

  # Database

  db:
    container_name: localsecrets_db
    image: postgis/postgis:14-3.3-alpine
    restart: unless-stopped
    volumes:
      - local-secrets-postgres-data:/var/lib/postgresql/data
    env_file: .docker/environments/local.env
    ports:
      - "5432:5432"

#  # Memcached
#
#  cache:
#    container_name: cache
#    image: memcached:1.6-alpine
#    ports:
#      - "11211:11211"
#    networks:
#      - netlink

#  # Redis
#
#  redis:
#    container_name: redis
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    networks:
#      - netlink

#  # Django RQ Worker
#
#  rqworker:
#    container_name: rqworker
#    image: base-project_app
#    env_file: .docker/environments/local.env
#    command: python manage.py show_urls
#    volumes:
#      - .:/code
#    network_mode: service:redis
#    depends_on:
#      - app

#  # Django RQ Scheduler
#
#  rqscheduler:
#    container_name: rqscheduler
#    image: base-project_app
#    env_file: .docker/environments/local.env
#    command: python manage.py rqscheduler -i 15
#    volumes:
#      - .:/code
#    network_mode: service:redis
#    depends_on:
#      - app

#  # Celery
#
#  celery:
#    container_name: celery
#    build:
#      dockerfile: .docker/celery/Dockerfile
#    env_file: .docker/environments/local.env
#    command: celery -A local_secrets worker -l info
#    network_mode: service:redis
#    volumes:
#      - .:/code
#    depends_on:
#      - app

volumes:
  local-secrets-postgres-data:
