# Generated by Django 3.2.25 on 2025-01-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('type', models.CharField(choices=[('solo', 'Solo'), ('familiar', 'Familiar'), ('business', 'Business'), ('romantic', 'Romantic'), ('group', 'Group')], max_length=100, verbose_name='Type')),
                ('initial_date', models.DateField(verbose_name='Initial Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('cities', models.ManyToManyField(to='cities.City', verbose_name='Cities')),
                ('stops', models.ManyToManyField(related_name='travels', through='travels.Stop', to='sites.Site', verbose_name='Stops')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
            },
        ),
    ]
