# Generated by Django 3.2.13 on 2023-06-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_auto_20230531_1147'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='stops',
            field=models.ManyToManyField(related_name='travels', to='sites.Site', verbose_name='Stops'),
        ),
    ]
