# Generated by Django 3.2.13 on 2023-06-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_auto_20230531_1147'),
        ('travels', '0002_alter_travel_stops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.travel')),
            ],
        ),
    ]
