# Generated by Django 3.2.13 on 2023-06-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='stops',
        ),
    ]
