# Generated by Django 3.2.13 on 2023-06-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_auto_20230531_1147'),
        ('travels', '0004_remove_travel_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='stops',
            field=models.ManyToManyField(related_name='travels', through='travels.Stop', to='sites.Site', verbose_name='Stops'),
        ),
    ]
