# Generated by Django 3.2.13 on 2023-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('place', 'Place'), ('event', 'Event')], default='place', max_length=100),
        ),
    ]
