# Generated by Django 3.2.13 on 2023-04-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20230405_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
