# Generated by Django 3.2.13 on 2023-04-19 06:35

import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='site_images'),
        ),
        migrations.AddField(
            model_name='site',
            name='media',
            field=models.FileField(null=True, upload_to='site_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'webm', 'mkv'])]),
        ),
    ]
