# Generated by Django 3.2.13 on 2023-04-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone'),
        ('sites', '0005_auto_20230419_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='tags',
            field=models.ManyToManyField(related_name='site_tags', to='users.Tag'),
        ),
        migrations.CreateModel(
            name='SpecialSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('initial_hour', models.TimeField(default='08:00')),
                ('end_hour', models.TimeField(default='23:00')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_schedules', to='sites.site')),
            ],
            options={
                'verbose_name': 'Special Schedule',
                'verbose_name_plural': 'Special Schedules',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sites.site')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='HourRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_hour', models.TimeField(default='08.00')),
                ('end_hour', models.TimeField(default='23:00')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='sites.schedule')),
            ],
            options={
                'verbose_name': 'Hour Range',
                'verbose_name_plural': 'Hour Ranges',
            },
        ),
    ]
