# Generated by Django 3.2.13 on 2023-04-19 07:51

import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20230419_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='site_images'),
        ),
        migrations.AlterField(
            model_name='site',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='site_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'webm', 'mkv'])]),
        ),
    ]
