# Generated by Django 3.2.13 on 2023-04-26 15:02

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20230419_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='image',
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='site_images')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sites.site')),
            ],
        ),
    ]
