# Generated by Django 3.2.13 on 2023-04-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_auto_20230426_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
