# Generated by Django 3.2.13 on 2023-04-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default='2023-04-26 13:00', verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
