# Generated by Django 3.2.13 on 2023-04-28 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0009_alter_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='users',
            field=models.ManyToManyField(related_name='fav_sites', through='sites.FavoriteSites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritesites',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='favoritesites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
