# Generated by Django 3.2.13 on 2023-04-28 10:28

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_alter_site_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='site_images'),
        ),
    ]
