# Generated by Django 3.2.13 on 2023-05-02 07:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230502_0914'),
        ('sites', '0012_alter_siteimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourrange',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='sites.schedule', verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='site',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='site_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'webm', 'mkv'])], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tags',
            field=models.ManyToManyField(related_name='site_tags', to='users.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('place', 'Place'), ('event', 'Event')], default='place', max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='specialschedule',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_schedules', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='sites.category', verbose_name='Category'),
        ),
    ]
