# Generated by Django 3.2.13 on 2023-05-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_comment_created_at'),
        ('sites', '0013_auto_20230502_0922'),
    ]

    operations = [
    ]
