# Generated by Django 3.2.13 on 2023-05-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('sites', '0013_auto_20230502_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='cities.address'),
        ),
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='cities.city'),
        ),
    ]
