# Generated by Django 3.2.13 on 2023-05-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_auto_20230503_1214'),
        ('sites', '0014_merge_0009_comment_created_at_0013_auto_20230502_0922'),
    ]

    operations = [
    ]
