# Generated by Django 3.2.13 on 2023-05-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_auto_20230505_1125'),
        ('sites', '0015_merge_20230503_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='sites', to='cities.city', verbose_name='City'),
        ),
    ]
