# Generated by Django 3.2.13 on 2023-05-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_alter_site_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
