# Generated by Django 3.2.13 on 2023-05-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0017_site_is_suggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='has_been_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
