# Generated by Django 3.2.13 on 2023-05-17 11:41

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0018_site_has_been_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='default_images')),
            ],
        ),
    ]
