# Generated by Django 3.2.13 on 2023-05-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0019_defaultimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contact phone'),
        ),
        migrations.AddField(
            model_name='site',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link'),
        ),
    ]
