# Generated by Django 3.2.13 on 2023-06-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0021_site_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_width', models.IntegerField(default=512)),
                ('min_height', models.IntegerField(default=512)),
                ('max_width', models.IntegerField(default=4096)),
                ('max_height', models.IntegerField(default=2160)),
            ],
        ),
    ]
