# Generated by Django 3.2.13 on 2023-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0023_auto_20230609_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='levels',
            field=models.ManyToManyField(to='sites.Level', verbose_name='Levels'),
        ),
    ]
