# Generated by Django 3.2.13 on 2023-06-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0024_site_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='sites.SubCategory', verbose_name='Subcategories'),
        ),
    ]
