# Generated by Django 3.2.13 on 2023-06-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0025_alter_site_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='frequency',
            field=models.CharField(default='never', max_length=100, verbose_name='Frequency'),
        ),
    ]
