# Generated by Django 3.2.13 on 2023-06-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0026_site_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesize',
            options={'verbose_name': 'Image Size', 'verbose_name_plural': 'Images Sizes'},
        ),
    ]
