# Generated by Django 3.2.13 on 2023-07-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0027_alter_imagesize_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Search level', 'verbose_name_plural': 'Search levels'},
        ),
    ]
