# Generated by Django 3.2.13 on 2023-07-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0029_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
