# Generated by Django 3.2.13 on 2023-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0030_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourrange',
            name='initial_hour',
            field=models.TimeField(default='08:00'),
        ),
    ]
