# Generated by Django 3.2.13 on 2023-07-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0031_alter_hourrange_initial_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_size', models.IntegerField(default=512)),
                ('max_size', models.IntegerField(default=4096)),
            ],
            options={
                'verbose_name': 'Video Size',
                'verbose_name_plural': 'Videos Sizes',
            },
        ),
    ]
