# Generated by Django 3.2.13 on 2023-07-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0032_videosize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
