# Generated by Django 3.2.20 on 2023-08-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0034_auto_20230803_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
