# Generated by Django 3.2.20 on 2023-08-03 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0035_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
    ]
