# Generated by Django 3.2.20 on 2023-09-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0036_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ('title',), 'verbose_name': 'Search level', 'verbose_name_plural': 'Search levels'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('title',), 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
    ]
