# Generated by Django 3.2.20 on 2023-10-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0037_auto_20230920_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(default='EN', max_length=500, verbose_name='Title EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_es',
            field=models.CharField(default='ES', max_length=500, verbose_name='Title ES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='title_en',
            field=models.CharField(default='EN', max_length=500, verbose_name='Title EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='title_es',
            field=models.CharField(default='ES', max_length=500, verbose_name='Title ES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='description_en',
            field=models.TextField(default='EN', verbose_name='Description EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='description_es',
            field=models.TextField(default='ES', verbose_name='Description ES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='title_en',
            field=models.CharField(default='EN', max_length=500, verbose_name='Title EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='title_es',
            field=models.CharField(default='ES', max_length=500, verbose_name='Title ES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_en',
            field=models.CharField(default='EN', max_length=500, verbose_name='Title EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_es',
            field=models.CharField(default='ES', max_length=500, verbose_name='Title ES'),
            preserve_default=False,
        ),
    ]
