# Generated by Django 3.2.20 on 2023-10-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_translatedfield_translation'),
        ('sites', '0038_auto_20231018_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='level',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='level',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='site',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='site',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='site',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='site',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title_es',
        ),
        migrations.CreateModel(
            name='TranslatedSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sites.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Translated Title')),
                ('description', models.TextField(verbose_name='Translated Description')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Translated Title')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sites.level')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Translated Title')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sites.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
