# Generated by Django 3.2.21 on 2024-01-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0040_auto_20231124_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='always_open',
            field=models.BooleanField(default=False, verbose_name='Always open'),
        ),
    ]
