# Generated by Django 3.2.21 on 2024-03-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0041_site_always_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_top_10',
            field=models.BooleanField(default=False, verbose_name='Is top 10'),
        ),
    ]
