# Generated by Django 3.2.21 on 2024-05-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0042_site_is_top_10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='frequency',
            field=models.CharField(choices=[('never', 'Does not repeat (Uses schedules)'), ('day', 'Every day'), ('week', 'Every week'), ('month', 'Every month'), ('year', 'Every year'), ('workday', 'Every working day')], default='never', max_length=100, verbose_name='Frequency'),
        ),
    ]
