# Generated by Django 3.2.21 on 2024-05-10 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0043_alter_site_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialHourRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_hour', models.TimeField(default='08:00')),
                ('end_hour', models.TimeField(default='23:00')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='sites.specialschedule', verbose_name='Schedule')),
            ],
        ),
    ]
