# Generated by Django 3.2.21 on 2024-09-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0045_auto_20240513_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='categories',
            field=models.ManyToManyField(related_name='sites', to='sites.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='site',
            name='levels',
            field=models.ManyToManyField(related_name='sites', to='sites.Level', verbose_name='Levels'),
        ),
        migrations.AlterField(
            model_name='site',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='sites', to='sites.SubCategory', verbose_name='Subcategories'),
        ),
    ]
