# Generated by Django 3.2.25 on 2024-10-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0047_auto_20240927_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='frequency',
            field=models.CharField(choices=[('never', 'Does not repeat (Uses schedules)'), ('day', 'Every day'), ('week', 'Every week'), ('year', 'Every year'), ('workday', 'Every working day')], default='never', max_length=100, verbose_name='Frequency'),
        ),
    ]
