# Generated by Django 3.2.25 on 2024-10-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0048_alter_site_frequency'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='translatedsite',
            index=models.Index(fields=['title', 'description'], name='sites_trans_title_43620e_idx'),
        ),
    ]
