# Generated by Django 3.2.25 on 2024-10-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0049_translatedsite_sites_trans_title_43620e_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='site',
            index=models.Index(condition=models.Q(('type', 'event')), fields=['frequency'], name='frequency_idx'),
        ),
    ]
