# Generated by Django 3.2.25 on 2024-10-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0050_site_frequency_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='translatedcategory',
            index=models.Index(fields=['title'], name='sites_trans_title_30274e_idx'),
        ),
        migrations.AddIndex(
            model_name='translatedlevel',
            index=models.Index(fields=['title'], name='sites_trans_title_bd2c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='translatedsubcategory',
            index=models.Index(fields=['title'], name='sites_trans_title_c4e31a_idx'),
        ),
    ]
