# Generated by Django 3.2.25 on 2025-01-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('back', 'Back')], max_length=100)),
                ('translation', models.FileField(upload_to='', verbose_name='Translation')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language', verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Translated Title')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('language_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('title', 'Title'), ('name', 'Name'), ('description', 'Description'), ('type', 'Type')], max_length=100)),
                ('translation', models.CharField(default='', max_length=5000)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language', verbose_name='Language')),
            ],
        ),
    ]
