# Generated by Django 3.2.20 on 2023-08-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk', models.IntegerField()),
                ('field', models.CharField(choices=[('title', 'Title'), ('name', 'Name'), ('description', 'Description'), ('type', 'Type')], max_length=100)),
                ('translation', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
