# Generated by Django 3.2.21 on 2023-09-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20230920_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedfield',
            name='translation',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
