# Generated by Django 3.2.21 on 2024-04-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_alter_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Translated Title')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('language_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='languages.language')),
            ],
        ),
    ]
