# Generated by Django 3.2.13 on 2023-05-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=18, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tags',
            field=models.ManyToManyField(through='users.UserTags', to='users.Tag', verbose_name='Tags'),
        ),
    ]
