# Generated by Django 3.2.13 on 2023-05-05 07:49

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230502_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='1', upload_to='pfp', verbose_name='Profile Picture'),
            preserve_default=False,
        ),
    ]
