# Generated by Django 3.2.13 on 2023-05-10 06:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230502_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=datetime.datetime(2023, 5, 10, 6, 39, 7, 662229, tzinfo=utc), verbose_name='Created at')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_been_seen', models.BooleanField(default=False, verbose_name='Has been seen')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.notification', verbose_name='Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Users Notification',
                'verbose_name_plural': 'Users Notifications',
            },
        ),
    ]
