# Generated by Django 3.2.13 on 2023-05-10 07:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_id',
            field=models.CharField(default='test', max_length=512, verbose_name='Device ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2023, 5, 10, 7, 22, 34, 881776, tzinfo=utc), verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.notification', verbose_name='Notification'),
        ),
    ]
