# Generated by Django 3.2.13 on 2023-05-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_picture'),
        ('users', '0006_alter_notification_created_at'),
    ]

    operations = [
    ]
