# Generated by Django 3.2.13 on 2023-05-24 13:59

from django.db import migrations
import local_secrets.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20230515_1304'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', local_secrets.users.managers.CustomUserManager()),
            ],
        ),
    ]
