# Generated by Django 3.2.20 on 2023-09-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_groupdescription_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_prefix',
            field=models.CharField(default='+34', max_length=6, verbose_name='Prefix'),
            preserve_default=False,
        ),
    ]
