# Generated by Django 3.2.20 on 2023-10-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_phone_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_prefix',
            field=models.CharField(max_length=10, verbose_name='Prefix'),
        ),
    ]
