# Generated by Django 3.2.20 on 2023-10-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_phone_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(default='EN', max_length=120, verbose_name='Tag EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='title_es',
            field=models.CharField(default='ES', max_length=120, verbose_name='Tag ES'),
            preserve_default=False,
        ),
    ]
