# Generated by Django 3.2.20 on 2023-10-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20231018_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdescription',
            name='description_en',
            field=models.TextField(default='Description', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupdescription',
            name='description_es',
            field=models.TextField(default='Descripción', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
