# Generated by Django 3.2.20 on 2023-10-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_translatedfield_translation'),
        ('users', '0018_auto_20231018_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdescription',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='groupdescription',
            name='description_es',
        ),
        migrations.CreateModel(
            name='TranslatedGroupDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Translated Description')),
                ('group_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='users.groupdescription')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
