# Generated by Django 3.2.21 on 2023-10-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20231018_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Device ID'),
        ),
    ]
