# Generated by Django 3.2.21 on 2024-05-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customuser_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedgroupdescription',
            name='name',
            field=models.CharField(default='test', max_length=150, verbose_name='Translated Name'),
            preserve_default=False,
        ),
    ]
