version: '3.3'

services:
  web:
    container_name: web
    restart: always  # Fixes occasional error: Conflict. The container name "/web" is already in use by container
    build:
      context: ..
      dockerfile: .docker/app/Dockerfile
      args:
        DEPLOYMENT_ENVIRONMENT: staging
    image: websource
    ports:
      - '127.0.0.1:8000:8000'
    env_file: environments/staging.env
    # --access-logfile=/var/log/nginx/access.log --error-logfile=/var/log/nginx/error.log --log-file=/var/log/nginx/nginx.log
    command: 'gunicorn config.wsgi:application -k gevent -w 3 -b :8000 --worker-connections=1000 --reload --capture-output --enable-stdio-inheritance --log-level=debug --access-logfile=- --log-file=-'
    volumes:
      - cachedata:/cache
      - mediadata:/code/media
      - staticdata:/code/static
    depends_on:
      - postgres
      - cache

  cache:
    restart: always
    container_name: cache
    image: memcached:1.6-alpine
    command: memcached -I 10m

  postgres:
    restart: always
    container_name: postgres
    image: postgis/postgis:14-3.3-alpine
    env_file: environments/staging.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx/staging/Dockerfile
      args:
        DEPLOYMENT_ENVIRONMENT: staging
    container_name: nginx
    cap_add:
      - NET_ADMIN
    environment: # https://github.com/linuxserver/docker-swag
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=localsecrets-staging.rudo.es
      - VALIDATION=http
      - EMAIL=fdosalom@gmail.com
      - STAGING=false # This option set to true is used to skip SSL cert generation
    volumes:
      - nginx:/config
      - staticdata:/static
      - mediadata:/media
    depends_on:
      - web
    ports:
      - '443:443'
      - '80:80' # optional

volumes:
  pgdata:
  cachedata:
  mediadata:
  staticdata:
  nginx:
