version: '3.3'

services:
  web:
    container_name: web
    restart: always  # Fixes occasional error: Conflict. The container name "/web" is already in use by container
    build:
      context: ..
      dockerfile: .docker/app/Dockerfile
      args:
        DEPLOYMENT_ENVIRONMENT: production
    image: websource
    ports:
      - '127.0.0.1:8000:8000'
    env_file: environments/production.env
    command: 'gunicorn config.wsgi:application -k gevent -w 3 -b :8000 --worker-connections=1000 --reload --capture-output --enable-stdio-inheritance --log-level=debug --access-logfile=- --log-file=-'
    volumes:
      - cachedata:/cache
      - mediadata:/code/media
      - staticdata:/code/static
      - wellknowndata:/code/.well-known
    depends_on:
      - postgres
      - cache

  cache:
    container_name: cache
    restart: always
    image: memcached:1.6-alpine
    command: memcached -I 10m

  postgres:
    container_name: postgres
    restart: always
    image: postgis/postgis:14-3.3-alpine
    env_file: environments/production.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx/production/Dockerfile
      args:
        DEPLOYMENT_ENVIRONMENT: production
    container_name: nginx
    cap_add:
      - NET_ADMIN
    environment: # https://github.com/linuxserver/docker-swag
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=app.localsecrets.travel
      - VALIDATION=http
      - EMAIL=fdosalom@gmail.com
    volumes:
      - nginx:/config
      - staticdata:/static
      - mediadata:/media
      - wellknowndata:/.well-known
    depends_on:
      - web
    ports:
      - '443:443'
      - '80:80' # optional

volumes:
  pgdata:
  cachedata:
  mediadata:
  staticdata:
  wellknowndata:
  nginx:
