# Generated by Django 3.2.20 on 2023-08-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0033_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.category',),
        ),
        migrations.CreateModel(
            name='LevelForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Search level',
                'verbose_name_plural': 'Search levels',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.level',),
        ),
        migrations.CreateModel(
            name='SubcategoryForAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.subcategory',),
        ),
    ]
