# Generated by Django 3.2.25 on 2025-01-29 08:15

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('cp', models.CharField(max_length=12, verbose_name='CP')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326, verbose_name='Geolocation')),
                ('description', models.TextField(verbose_name='Description')),
                ('slogan', models.CharField(max_length=100, verbose_name='Slogan')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link')),
                ('media', models.FileField(blank=True, null=True, upload_to='site_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'webm', 'mkv'])], verbose_name='Video')),
                ('latitude', models.DecimalField(blank=True, decimal_places=27, default=0, max_digits=30, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=27, default=0, max_digits=30, verbose_name='Longitude')),
                ('activated', models.BooleanField(default=True, verbose_name='Is active?')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('code', models.CharField(max_length=3, verbose_name='ISO Code')),
                ('phone_code', models.CharField(default=34, max_length=10, verbose_name='Phone code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('code', models.CharField(max_length=3, verbose_name='ISO Code')),
                ('phone_code', models.CharField(default=34, max_length=10, verbose_name='Phone code')),
            ],
            options={
                'verbose_name': 'Phone Code',
                'verbose_name_plural': 'Phone Code',
            },
        ),
        migrations.CreateModel(
            name='TranslatedPhoneCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Translated Name')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('phone_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cities.phonecode')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Translated Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cities.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('description', models.TextField(verbose_name='Description')),
                ('slogan', models.CharField(max_length=100, verbose_name='Slogan')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cities.city')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='city_images', verbose_name='Image')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cities.city', verbose_name='City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.country', verbose_name='Country'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250, verbose_name='Street')),
                ('cp', models.CharField(max_length=12, verbose_name='CP')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326, verbose_name='Geolocation')),
                ('latitude', models.DecimalField(blank=True, decimal_places=27, default=0, max_digits=30, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=27, default=0, max_digits=30, verbose_name='Longitude')),
                ('google_place_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Google Place Id')),
                ('details', models.CharField(blank=True, max_length=500, null=True, verbose_name='Details')),
                ('number', models.CharField(blank=True, max_length=6, null=True, verbose_name='Number')),
                ('door', models.CharField(blank=True, max_length=6, null=True, verbose_name='Door')),
                ('floor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Floor')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='cities.city')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
