# Generated by Django 3.2.13 on 2023-05-05 07:14

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20230503_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='city_images'),
        ),
    ]
