# Generated by Django 3.2.13 on 2023-05-05 09:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_alter_cityimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='address',
            name='door',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Door'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='address',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Google Place Id'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Geolocation'),
        ),
        migrations.AlterField(
            model_name='city',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Geolocation'),
        ),
        migrations.AlterField(
            model_name='cityimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='city_images', verbose_name='Image'),
        ),
    ]
