# Generated by Django 3.2.13 on 2023-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_alter_city_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slogan',
            field=models.CharField(default='Sol y vino', max_length=100, verbose_name='Slogan'),
            preserve_default=False,
        ),
    ]
