# Generated by Django 3.2.13 on 2023-07-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_city_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cp',
            field=models.CharField(default=0, max_length=12, verbose_name='CP'),
            preserve_default=False,
        ),
    ]
