# Generated by Django 3.2.13 on 2023-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_address_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=3, verbose_name='ISO Code'),
        ),
    ]
