# Generated by Django 3.2.13 on 2023-07-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_alter_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug_latitude',
            field=models.SlugField(default=0, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='city',
            name='slug_longitude',
            field=models.SlugField(default=0, verbose_name='Longitude'),
        ),
    ]
