# Generated by Django 3.2.13 on 2023-07-25 11:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_auto_20230725_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326, verbose_name='Geolocation'),
        ),
    ]
