# Generated by Django 3.2.13 on 2023-07-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0013_alter_city_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(default=34, max_length=10, verbose_name='Phone code'),
        ),
    ]
