# Generated by Django 3.2.13 on 2023-07-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0014_country_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=27, default=0, max_digits=30, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=27, default=0, max_digits=30, verbose_name='Longitude'),
        ),
    ]
