# Generated by Django 3.2.13 on 2023-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_auto_20230728_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=27, default=0, max_digits=30, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=27, default=0, max_digits=30, verbose_name='Longitude'),
        ),
    ]
