# Generated by Django 3.2.13 on 2023-07-28 08:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0016_auto_20230728_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326, verbose_name='Geolocation'),
        ),
    ]
