# Generated by Django 3.2.20 on 2023-08-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0017_alter_address_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
