# Generated by Django 3.2.20 on 2023-08-02 09:06

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0018_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
