# Generated by Django 3.2.20 on 2023-10-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0019_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-04 17:08', verbose_name='Creation date'),
            preserve_default=False,
        ),
    ]
