# Generated by Django 3.2.20 on 2023-10-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_translatedfield_translation'),
        ('cities', '0021_auto_20231018_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='city',
            name='province_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='province_es',
        ),
        migrations.RemoveField(
            model_name='city',
            name='slogan_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='slogan_es',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_es',
        ),
        migrations.CreateModel(
            name='TranslatedCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Translated Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cities.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('description', models.TextField(verbose_name='Description')),
                ('slogan', models.CharField(max_length=100, verbose_name='Slogan')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cities.city')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
        ),
    ]
