# Generated by Django 3.2.21 on 2023-12-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0023_city_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
    ]
