# Generated by Django 3.2.21 on 2023-12-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0024_alter_city_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='is_active',
        ),
    ]
