# Generated by Django 3.2.21 on 2024-02-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0025_remove_city_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('code', models.CharField(max_length=3, verbose_name='ISO Code')),
                ('phone_code', models.CharField(default=34, max_length=10, verbose_name='Phone code')),
            ],
            options={
                'verbose_name': 'Phone Code',
                'verbose_name_plural': 'Phone Code',
            },
        ),
    ]
