# Generated by Django 3.2.21 on 2024-02-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_translatedfield_translation'),
        ('cities', '0026_phonecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedPhoneCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Translated Name')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('phone_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cities.phonecode')),
            ],
        ),
    ]
