# Generated by Django 3.2.21 on 2024-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0027_translatedphonecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='activated',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
    ]
